siteTitle="React Sharingbuttons"
baseColor = "#1B5E20"
linkPrefix = "/react-sharingbuttons"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
]
siteUrl = "https://github.com/caspg"
repoUrl = "https://github.com/caspg/react-sharingbuttons"
